package GameQR;


public class TestQuestion
{
    public static void main(String[] args) {
        Questions question1 = new Questions("Vocabulaire","difficile","Qu'est-ce que le monophylétisme ?","Théorie de laquelle les hommes dérivent du même ancêtre");
        Questions question2 = new Questions("Vocabulaire","moyen","Qu'est-ce que la déontologie ?","Le code de conduite d'une profession");
        Questions question3 = new Questions("Vocabulaire","facile","Que signifie le verbe enrêner ?","Mettre des rênes");
        Questions question4 = new Questions("Vocabulaire","facile","Le terme univoque signifie qu'il n'a aucun sens","VRAI");
        Questions question5 = new Questions("Vocabulaire","difficile","Une personne dont laquelle la langue maternelle n'est pas celle de la communauté dans laquelle elle vit est allophone ?","VRAI");
        Questions question6 = new Questions("Vocabulaire","moyen","Le ménure est un arbre","FAUX");
        Questions question7 = new Questions("Vocabulaire","moyen","Une attitude hiératique est : ","solennelle");
        Questions question8 = new Questions("Vocabulaire","facile","L'action de s'imbiber est l'imbibition ?","VRAI");
        Questions question9 = new Questions("Vocabulaire","facile","Donner le participe présent du verbe impressionener ","impressionnant");
        Questions question10 = new Questions("Vocabulaire","moyen","Conjuguez le verbe boire au conditionnel présent, à la 1ère personne du pluriel","nous boirions");
        Questions question11 = new Questions("Mathématiques","facile","Combien font (7+5*6) ?","37");
        Questions question12 = new Questions("Mathématiques","moyen","Un objet coûte 135€, il y une réduction de 20%, quel est le nouveau ? ","108");
        Questions question13 = new Questions("Mathématiques","difficile","Donner l'aire d'un triangle","(base*hauteur)/2");
        Questions question14 = new Questions("Mathématiques","facile","Est-il possible de simpllifier la fraction suivante (310/60)","VRAI");
        Questions question15 = new Questions("Mathématiques","moyen","Quelle est l'aire de toutes les faces d'un cube de 2cm de côté","24cm^2");
        Questions question16 = new Questions("Mathématiques","moyen","Le plus petit nombre entier de 5 chiffres que l'on peut écrire avec les chiffres 0,3,7,5 et 2 est : ","20 357");
        Questions question17 = new Questions("Mathématiques","difficile","Quel est le premier nombre premier supérieur à 20 ?","23");
        Questions question18 = new Questions("Mathématiques","facile","Une droite qui sépare un angle en 2 angles adjacents de même mesure est une bissectrice ? ","VRAI");
        Questions question19 = new Questions("Mathématiques","moyen","Quel nombre est égal à 9 fois racine de 9 ?","27");
        Questions question20 = new Questions("Mathématiques","facile","Deux droites qui se coupent de manière quelconque sont sécantes ?","VRAI");
        Questions question21 = new Questions("Histoire","moyen","Dans quel pays la locomotive à vapeur fut-elle inventée ?","Grande Bretagne");
        Questions question22 = new Questions("Histoire","facile","Qui fut l'avocat et le principal soutien de Dreyfus en 1898 ?","Emile Zola");
        Questions question23 = new Questions("Histoire","difficile","Après la guerre d'Afghanistan et les coûts engendrés par la catastrophe de Tchernobyl, affaiblie et instable politiquement, l'URSS éclate. C'était en quelle année ?","1991");
        Questions question24 = new Questions("Histoire","facile","Le STO durant une certaine période du XXème siècle signifiait 'service de travail obligatoire' ?","VRAI");
        Questions question25 = new Questions("Histoire","moyen","En quelle année a eu lieu la 'Grande Dépression ?","1929");
        Questions question26 = new Questions("Histoire","difficile","Le pays qui a envahi l'Ethiopie en 1935-1936 est le Royaume-Uni ?","FAUX");
        Questions question27 = new Questions("Histoire","facile","Que vient de rompre Hitler lorsque le 22 juin 1941 il envahit l'URSS ?","Le pacte de non-agression conclu avec Staline ?");
        Questions question28 = new Questions("Histoire","moyen","En quelle année a eu lieu l'armistice du 11 novembre ?","1945");
        Questions question29 = new Questions("Histoire","facile","Le Roi Soleil était Louis XIV ?","VRAI");
        Questions question30 = new Questions("Histoire","moyen","Comment le règne de Louis XIV est-il qualifié ?","Monarchie absolue de droit divin");
        Questions question31 = new Questions("Géographie","difficile","Quelle ville se situe le plus au nord ?","Lyon");
        Questions question32 = new Questions("Géographie","moyen","Quel est le fleuve le plus long de France ?","Le Rhône");
        Questions question33 = new Questions("Géographie","difficile","La Belgique est le surnommé le plat plays","VRAI");
        Questions question34 = new Questions("Géographie","difficile","Quelle est la capitale de la Lituanie ?","Vilnius");
        Questions question35 = new Questions("Géographie","facile","Quelle est la capitale du Danemark ?","Copenhague");
        Questions question36 = new Questions("Géographie","moyen","La pays du matin calme est la Corée","VRAI");
        Questions question37 = new Questions("Géographie","facile","Le pays des kangourous est : ","Australie");
        Questions question38 = new Questions("Géographie","facile","Avec quel pays la frontière de la France est-elle la plus courte ?","Belgique");
        Questions question39 = new Questions("Géographie","moyen","Le département qui a la plu grande superficie est le Bas-Rhin ?","FAUX");
        Questions question40 = new Questions("Géographie","facile","Quelle est la capitale des Etats*Unis","Washington");
        Questions question41 = new Questions("Science","facile","Le cerveau est un élément du : ","Système nerveux");
        Questions question42 = new Questions("Science","moyen","Il n'y a pas de glace dans l'espace","FAUX");
        Questions question43 = new Questions("Science","difficile","La planète la plus proche de la Terre est Mars","FAUX");
        Questions question44 = new Questions("Science","moyen","L'artère la plus grosse de notre corps est l'artère ...","aorte");
        Questions question45 = new Questions("Science","moyen","A quoi est due la couleur rouge du sand ?"," L'hémoglobine");
        Questions question46 = new Questions("Science","difficile","Quelle catégorie de tissu du système nerveux au niveau de l'encéphale le cortex désigne-t-il ?","Subtance grise");
        Questions question47 = new Questions("Science","facile","L'organe qui filtre le sang et excrète les déchets de l'organisme sous forme d'urine est : ","Le rein");
        Questions question48 = new Questions("Science","facile","C'est durant l'hiver (dans l'hémisphère nord) que la Terre est la plus rapprochée du Soleil","FAUX");
        Questions question49 = new Questions("Science","facile","La température dans est de 0 degré","FAUX");
        Questions question50 = new Questions("Science","moyen","Combien y a-t-il d'hémisphères cérébrraux chez l'Homme","2");
        Questions question51 = new Questions("Sport","difficile","La 1ère édition de la coupe du monde était en :","1930");
        Questions question52 = new Questions("Sport","facile","En 1950, le Brésil a été désigné hôte pour la coupe la 1ère fois, en quelle année fut-il une seconde fois hôte ?","2014");
        Questions question53 = new Questions("Sport","moyen","Le pyas d'origine du handball est l'Allemagne ?","FAUX");
        Questions question54 = new Questions("Sport","facile","Combien y a-t-il d'arbitre lors d'un match de handball ?","2");
        Questions question55 = new Questions("Sport","difficile","Le diamètre d'un panier de basket est de 18 pouces","FAUX");
        Questions question56 = new Questions("Sport","moyen","Pour gagner un set au volley, il faut marquer 20 points","FAUX");
        Questions question57 = new Questions("Sport","facile","Combien dure une prologation d'un match de foot ?","30");
        Questions question58 = new Questions("Sport","moyen","C'est souvent un crochet qui met fin à ce sport","Le judo");
        Questions question59 = new Questions("Sport","moyen","Dans ce sport, on peut, à l'occasion, pratiquer le ciseau retourné","Le football");
        Questions question60 = new Questions("Sport","facile","Qui a gagné le plus de ballon d'or dans l'histoire du football","Messi");
        Questions question61 = new Questions("Cinéma","facile","Il y a 9 saisons dans 'FRIENDS' ?","FAUX");
        Questions question62 = new Questions("Cinéma","moyen","Combien y a-t-il de saison dans les Simpson ?","32");
        Questions question63 = new Questions("Cinéma","facile","Quel est le nom du film où un bateau coule ?","Titanic");
        Questions question64 = new Questions("Cinéma","moyen","Combien y a-t-il de 'Fast and Furious' ?","9");
        Questions question65 = new Questions("Cinéma","moyen","Le dessin animée 'Le Roi Lion' a décroché un Oscar","VRAI");
        Questions question66 = new Questions("Cinéma","difficile","Le premier film Disney est apparu en 1928","VRAI");
        Questions question67 = new Questions("Cinéma","facile","Quel est le méchant de la saga 'Star-Wars' ?","Dark Vador");
        Questions question68 = new Questions("Cinéma","difficile","Les masques dans la série 'Casa de Papel' sont inspirés de l'artiste :","Salvador Dali");
        Questions question69 = new Questions("Cinéma","facile","Quel est le thème de la série Grey Anatomy ?","Médecine");
        Questions question70 = new Questions("Cinéma","moyen","Comment s'appelle la fée dans Cendrillon ?","Fée Marraine");
        Questions question71 = new Questions("Culture Générale","moyen","Quel pays ne fait pas partie de l'UE ?","Norvège");
        Questions question72 = new Questions("Culture générale","moyen","Dans quelle ville le Parlement européen se situe-t-il ?","Strasbourg");
        Questions question73 = new Questions("Culture générale","facile","Les accords de Schengen correspondent à la suppression des barrières douanières","VRAI");
        Questions question74 = new Questions("Culture générale","difficile","En quelle année la peine de mort a-t-elle été abolie en France ?","1981");
        Questions question75 = new Questions("Culture générale","facile","En quelle année le droit de vote a été accordé aux femmes en France ?","1945");
        Questions question76 = new Questions("Culture générale","difficile","Le mur de Berlin est tombé en ...","1989");
        Questions question77 = new Questions("Culture générale","moyen","Le roi qui fut guillotiné le 21 janvier 1793 est Louis XV","VRAI");
        Questions question78 = new Questions("Culture générale","facile","Qui est l'auteur du roman 'Germinal' ?","Emile Zola");
        Questions question79 = new Questions("Culture générale","moyen","L'adjectif 'imminent' signifie 'très proche'","VRAI");
        Questions question80 = new Questions("Culture générale","moyen","Faire preuve d'abnégation, c'est","Se dévouer avec désintéressement");
        Questions question81 = new Questions("Nature","facile","La tomate est un fruit","VRAI");
        Questions question82 = new Questions("Nature","facile","Avec quelle partie de son corps, le serpent à sonnettes fait-il du bruit ?","La queue");
        Questions question83 = new Questions("Nature","moyen","Quelle partie de la carotte mange-t-on ?","La racine");
        Questions question84 = new Questions("Nature","moyen","L'insecte qui transmet le paludisme est la sauterelle","FAUX");
        Questions question85 = new Questions("Nature","facile","Quel mot désigne l'ensemble des plantes dans un endroit ?","La flore");
        Questions question86 = new Questions("Nature","difficile","Un phycoloque étudie les algues ?","VRAI");
        Questions question87 = new Questions("Nature","difficile","Quelle est la couleur de la peau de l'ours blanc ?","Noir");
        Questions question88 = new Questions("Nature","moyen","Combien de bras a une étoile de mer ?","8");
        Questions question89 = new Questions("Nature","moyen","Combien de pic a un hérisson ?","5000");
        Questions question90 = new Questions("Nature","facile","Quel animal est le plus rapide","Le guépard");
        Questions question91 = new Questions("Informatique","facile","Quel est le langage informatique le plus courant pour écrire les pages web ?","HTML");
        Questions question92 = new Questions("Informatique","facile","A quoi est égal 1 octet à combien de bits ?","8");
        Questions question93 = new Questions("Informatique","moyen","Qu'est-ce qu'une adresse IP ?","Un numéro qui identifie chaque matériel informatique");
        Questions question94 = new Questions("Informatique","moyen","Un CPU est-il un processeur ?","VRAI");
        Questions question95 = new Questions("Informatique","difficile","Comment appelle-t-on un logiciel dont l'utilisateur doit rétribuer l'auteur s'il veut continuer à l'utiliser après une période de gratuité ?","Un shareware");
        Questions question96 = new Questions("Informatique","facile","Le langage le plus connu et utilisé au monde est JAVA","VRAI");
        Questions question97 = new Questions("Informatique","facile","La RAM (Random Access Memory) est la mémoire vive ?","VRAI");
        Questions question98 = new Questions("Informatique","moyen","HTTP est un protocole de communication client-serveur et signifie ...","HyperText Transfer Protocol");
        Questions question99 = new Questions("Informatique","moyen","Quand a été inventé internet ?","1969");
        Questions question100 = new Questions("Informatique","difficile","Quand e été inventé la souris ?","1963");


        Questions.addQuestion(question1.getQuestion());
        Questions.addQuestion(question2.getQuestion());
        Questions.addQuestion(question3.getQuestion());
        Questions.addQuestion(question4.getQuestion());
        Questions.addQuestion(question5.getQuestion());
        Questions.addQuestion(question6.getQuestion());
        Questions.addQuestion(question7.getQuestion());
        Questions.addQuestion(question8.getQuestion());
        Questions.addQuestion(question9.getQuestion());
        Questions.addQuestion(question10.getQuestion());
        Questions.addQuestion(question11.getQuestion());
        Questions.addQuestion(question12.getQuestion());
        Questions.addQuestion(question13.getQuestion());
        Questions.addQuestion(question14.getQuestion());
        Questions.addQuestion(question15.getQuestion());
        Questions.addQuestion(question16.getQuestion());
        Questions.addQuestion(question17.getQuestion());
        Questions.addQuestion(question18.getQuestion());
        Questions.addQuestion(question19.getQuestion());
        Questions.addQuestion(question20.getQuestion());
        Questions.addQuestion(question21.getQuestion());
        Questions.addQuestion(question22.getQuestion());
        Questions.addQuestion(question23.getQuestion());
        Questions.addQuestion(question24.getQuestion());
        Questions.addQuestion(question25.getQuestion());
        Questions.addQuestion(question26.getQuestion());
        Questions.addQuestion(question27.getQuestion());
        Questions.addQuestion(question28.getQuestion());
        Questions.addQuestion(question29.getQuestion());
        Questions.addQuestion(question30.getQuestion());
        Questions.addQuestion(question31.getQuestion());
        Questions.addQuestion(question32.getQuestion());
        Questions.addQuestion(question33.getQuestion());
        Questions.addQuestion(question34.getQuestion());
        Questions.addQuestion(question35.getQuestion());
        Questions.addQuestion(question36.getQuestion());
        Questions.addQuestion(question37.getQuestion());
        Questions.addQuestion(question38.getQuestion());
        Questions.addQuestion(question39.getQuestion());
        Questions.addQuestion(question40.getQuestion());
        Questions.addQuestion(question41.getQuestion());
        Questions.addQuestion(question42.getQuestion());
        Questions.addQuestion(question43.getQuestion());
        Questions.addQuestion(question44.getQuestion());
        Questions.addQuestion(question45.getQuestion());
        Questions.addQuestion(question46.getQuestion());
        Questions.addQuestion(question47.getQuestion());
        Questions.addQuestion(question48.getQuestion());
        Questions.addQuestion(question49.getQuestion());
        Questions.addQuestion(question50.getQuestion());
        Questions.addQuestion(question51.getQuestion());
        Questions.addQuestion(question52.getQuestion());
        Questions.addQuestion(question53.getQuestion());
        Questions.addQuestion(question54.getQuestion());
        Questions.addQuestion(question55.getQuestion());
        Questions.addQuestion(question56.getQuestion());
        Questions.addQuestion(question57.getQuestion());
        Questions.addQuestion(question58.getQuestion());
        Questions.addQuestion(question59.getQuestion());
        Questions.addQuestion(question60.getQuestion());
        Questions.addQuestion(question61.getQuestion());
        Questions.addQuestion(question62.getQuestion());
        Questions.addQuestion(question63.getQuestion());
        Questions.addQuestion(question64.getQuestion());
        Questions.addQuestion(question65.getQuestion());
        Questions.addQuestion(question66.getQuestion());
        Questions.addQuestion(question67.getQuestion());
        Questions.addQuestion(question68.getQuestion());
        Questions.addQuestion(question69.getQuestion());
        Questions.addQuestion(question70.getQuestion());

        Questions.TabQuestions();

        System.out.println("-----------------Choississez vos questions aléatoirement-------------------");

        Questions.selectQuestion();


    }
}
